version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: curve25519-dalek
    versions:
    - 3.0.2
  - dependency-name: rand_core
    versions:
    - 0.6.1
  - dependency-name: sha2
    versions:
    - 0.9.2
